// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Activity: typeof import('./src/components/UserCentre/Activity.vue')['default']
    AddValue: typeof import('./src/components/Purse/AddValue.vue')['default']
    Banner: typeof import('./src/components/Index/Banner.vue')['default']
    Cards: typeof import('./src/components/Index/Cards.vue')['default']
    ChangePassword: typeof import('./src/components/Forms/ChangePassword.vue')['default']
    Credit: typeof import('./src/components/Commission/Credit.vue')['default']
    EditProfile: typeof import('./src/components/Forms/EditProfile.vue')['default']
    Follow: typeof import('./src/components/Index/Follow.vue')['default']
    FooterCP: typeof import('./src/components/Footer/FooterCP.vue')['default']
    FooterIndex: typeof import('./src/components/Footer/FooterIndex.vue')['default']
    FooterSp: typeof import('./src/components/Footer/FooterSp.vue')['default']
    ForgetPassword: typeof import('./src/components/Forms/ForgetPassword.vue')['default']
    Friends: typeof import('./src/components/Commission/Friends.vue')['default']
    GamesCollection: typeof import('./src/components/Collect/GamesCollection.vue')['default']
    HeaderCP: typeof import('./src/components/Header/HeaderCP.vue')['default']
    HeaderIndex: typeof import('./src/components/Header/HeaderIndex.vue')['default']
    HeaderLogin: typeof import('./src/components/Header/HeaderLogin.vue')['default']
    Index: typeof import('./src/components/Account/Index.vue')['default']
    Login: typeof import('./src/components/Forms/Login.vue')['default']
    MenuList: typeof import('./src/components/UserCentre/MenuList.vue')['default']
    MyFollow: typeof import('./src/components/MyStack/MyFollow.vue')['default']
    NewsCollection: typeof import('./src/components/Collect/NewsCollection.vue')['default']
    NewsList: typeof import('./src/components/Index/NewsList.vue')['default']
    Records: typeof import('./src/components/Purse/Records.vue')['default']
    Register: typeof import('./src/components/Forms/Register.vue')['default']
    RegisterValidate: typeof import('./src/components/Forms/Validate/RegisterValidate.vue')['default']
    ResetPassword: typeof import('./src/components/Forms/ResetPassword.vue')['default']
    Result: typeof import('./src/components/Account/Result.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Schedule: typeof import('./src/components/MyStack/Schedule.vue')['default']
    TopNews: typeof import('./src/components/Index/TopNews.vue')['default']
    Track: typeof import('./src/components/MyStack/Track.vue')['default']
    Transfer: typeof import('./src/components/Purse/Transfer.vue')['default']
    Unvertify: typeof import('./src/components/Login/Unvertify.vue')['default']
    VertifyEmail: typeof import('./src/components/Forms/VertifyEmail.vue')['default']
  }
}
